# Generated by Django 3.0.8 on 2020-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.AddField(
            model_name='account',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
