# Generated by Django 3.0.8 on 2020-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200701_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
